# Generated by Django 5.0.6 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_details',
            name='IFSC_CODE',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
