# Generated by Django 5.0.6 on 2024-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_rename_scrap_type_user_scrapdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_scrapdetails',
            name='Scrap_Image_Base64',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
