# Generated by Django 5.1.1 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.BigIntegerField(default=True),
        ),
    ]
