# Generated by Django 5.0.6 on 2024-10-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_user_scrapdetails_scrap_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
