# Generated by Django 5.1.1 on 2024-10-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_userprofile_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account',
            new_name='active',
        ),
    ]
