# Generated by Django 5.1.1 on 2024-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_rename_account_userprofile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountHolderName', models.CharField(max_length=50)),
                ('accountNumber', models.IntegerField(null=True)),
                ('bankName', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(null=True)),
            ],
        ),
    ]
