# Generated by Django 5.0.6 on 2024-10-28 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_remove_userlocation_user_id_userlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap_selection',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrap_selection',
            name='order_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scrap_selection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
