# Generated by Django 5.1.1 on 2024-10-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0006_bankdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='accountHolderName',
            new_name='account_holder_name',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bankName',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
