# Generated by Django 5.1.1 on 2024-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_rename_accountholdername_bankdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
