# Generated by Django 5.1.1 on 2024-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_alter_bankdetails_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base64File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField()),
            ],
        ),
    ]
