# Generated by Django 5.1.1 on 2024-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0010_alter_scrap_type_scrap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap_type',
            name='Scrap_Image',
            field=models.CharField(max_length=2000),
        ),
    ]
