# Generated by Django 5.1.1 on 2024-10-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0012_alter_scrap_type_scrap_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScrap_Type',
            fields=[
                ('Scrap_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Scrap_Name', models.CharField(max_length=50)),
                ('Current_Price_Per_KG', models.IntegerField(null=True)),
                ('Scrap_Image', models.TextField()),
                ('Price_Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
