# Generated by Django 5.1.1 on 2024-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0013_userscrap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap_type',
            name='Current_Price_Per_KG',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='userscrap_type',
            name='Current_Price_Per_KG',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
