# Generated by Django 5.0.6 on 2025-01-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0017_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerprofile',
            old_name='Natioanality',
            new_name='Nationality',
        ),
    ]
