# Generated by Django 5.1 on 2025-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0018_rename_natioanality_dealerprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='account',
            field=models.BooleanField(default=True),
        ),
    ]
